# Repaso de Python


## Ejercicio 1
Investigue/repase que son las listas, tuplas, conjuntos y diccionarios nativos de Python

* Listas
  * estructura de datos dinámica, mutable, heterogénea.
  * Es iterable y se puede acceder a sus elementos mediante un índice.
  * Se definen por medio de corchetes y sus elementos se separan por comas.
* Tuplas
  * Similar a la lista, pero es inmutable.
  * Es iterable y sus elementos se pueden acceder por medio de notación de corchetes e índice.
* Diccionarios
  * Contienen una colección de elementos de la forma 'clave: valor'.
  * Los valores se acceden mediante clave.

In [ ]:
# Utilizando los constructores para cada tipo de dato genere códigos de ejemplo y recórralos imprimiendo sus valores.

lista = [1,2,3,4,5]

for x in lista:
  print(x)

1
2
3
4
5


In [ ]:
tupla = (6,7,8,9,10)

for x in tupla:
  print(x)

6
7
8
9
10


In [ ]:
diccionario = {"uno":1, "dos":2, "tres":3, "cuatro":4, "cinco":5}

for key, value in diccionario.items():
  print(key, value)

uno 1
dos 2
tres 3
cuatro 4
cinco 5


## Ejercicio 2

Genere el código necesario para recorrer simultáneamente 2 listas con la misma cantidad de elementos e imprima
los mismos utilizando un único for (tip: función zip).

In [ ]:
frutas = ['manzana', 'banana','pera','cereza']
precios = [10, 20, 30, 40]
prueba = ['uno','dos','tres', 'cuatro']

for item in zip(frutas, precios, prueba):
  print(item)

('manzana', 10, 'uno')
('banana', 20, 'dos')
('pera', 30, 'tres')
('cereza', 40, 'cuatro')


## Ejercicio 3

Implemente una función que a partir de la lista que recibe cómo parámetro, retorne una nueva lista sin elementos
repetidos. Compruebe su correcto funcionamiento.

In [ ]:
repetidos = [9,8,3,45,1,8,4,3,1,1,1,20,9,15,5,6,7,12,4]

def eliminar_repetidos(lista):
  return list(set(lista))

eliminar_repetidos(repetidos)

[1, 3, 4, 5, 6, 7, 8, 9, 12, 45, 15, 20]

## Ejercicio 4

Implemente una función que calcule la distancia entre 2 puntos (2D). Utilice la función sqrt del paquete math para implementarla y compruebe el correcto funcionamiento de la misma.


**sqrt()** Para calcular la raíz cuadrada de un número.

*Distancia entre dos puntos: calcular los cuadrados de las diferencias entre sus coordenadas y luego hallar la raíz de la suma de dichos cuadrados.*


In [ ]:
import math
import collections

Punto = collections.namedtuple('Punto',['x','y'])

def calcular_distancia(punto1, punto2):
  return math.sqrt((punto2.x - punto1.x)**2 + (punto2.y - punto1.y)**2)

punto1 = Punto(-1,7)
punto2 = Punto(3,4)

calcular_distancia(punto1, punto2)

5.0

## Ejercicio 5

Investigue y escriba código que demuestre el funcionamiento de los “slices” en listas.

**Slices:** son una herramienta que permite extraer porciones de secuencias como listas, tuplas o cadenas con muy poco código.

Permiten trabajar con fragmentos específicos de una secuencia sin tener que modificar la original.

Sintaxis básica:

  **secuencia[inicio : fin : paso]**

  **inicio:** Índice donde comienza el slice (incluido).

  **fin:** Índice donde termina el slice (excluido).
  
  **paso:** Tamaño del paso o incremento entre elementos del slice (opcional).

In [ ]:
repetidos

[9, 8, 3, 45, 1, 8, 4, 3, 1, 1, 1, 20, 9, 15, 5, 6, 7, 12, 4]

In [ ]:
primeros_dos = repetidos[:2]

primeros_dos

[9, 8]

In [ ]:
ultimos_dos = repetidos[-2:]

ultimos_dos

[12, 4]

In [ ]:
menos_ultimos_dos = repetidos[:-2]

menos_ultimos_dos

[9, 8, 3, 45, 1, 8, 4, 3, 1, 1, 1, 20, 9, 15, 5, 6, 7]

In [ ]:
cinco_a_siete = repetidos[4:7]

cinco_a_siete

[1, 8, 4]

In [ ]:
inverso = repetidos[::-1]

inverso

[4, 12, 7, 6, 5, 15, 9, 20, 1, 1, 1, 3, 4, 8, 1, 45, 3, 8, 9]

In [ ]:
salto = repetidos[3:16:3]

salto

[45, 4, 1, 9, 6]

In [ ]:
dos_en_dos = repetidos[::2]

dos_en_dos

[9, 3, 1, 4, 1, 1, 9, 5, 7, 4]

In [ ]:
nuevo = [x for x in range(20)]

nuevo[2:10] = [22,44]

nuevo

[0, 1, 22, 44, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

# Biblioteca Numpy

## Ejercicio 1 - creación de vectores, matrices y tensores

* **¿Qué diferencias hay entre los constructores, array, empty, full, zeros, ones, identity?**

  * **Array:** son estructuras numéricas similares a las listas en python. De hecho, tienen propiedades muy parecidas, como mutabilidad, y permiten hacer slicing.
  
    * *Son más rápidos y compactos que las listas.*

  * **empty():** función que se utiliza para crear un array sin inicializar sus elementos con un valor en particular. Dependiendo del estado de la memoria, se va a inicializar con *basura o valores random*.

    * Son útiles cuando los valores van a ser sobreescritos luego de la inicialización.
    * *Syntaxis: numpy.empty(shape, dtype=float, order=’C’)*
      * Shape: tamaño del array. Puede ser un enetero o una tupla de enteros.
      * Dtype: es opcional. El tipo de dato por defecto es float.
      * Order: es opcional. Especifica el diseño de memoria de la matriz. Es C por defecto.  

  * **full():** Se usa para crear una array relleno con un valor específico constante.
    * Útil cuando quiero crear un array ya inicializado con un valor constante.
    * *Sintaxis: numpy.full(shape, fill_value, dtype=None, order=’C’)*
      * fill_value: El valor con el que quiero inicializar el array.

  * **zeros():** Para crear un array relleno de ceros.
    * *Sintaxis: numpy.zeros(shape, dtype=float, order=’C’)*

  * **ones():** Para crear un array relleno de unos.
    * *Sintaxis: numpy.ones(shape, dtype=None, order=’C’)*
  
  * **eye():** Para crear un array de 2 dimensiones, cuya diagonal tiene unos y el resto está relleno de ceros (matriz identidad).
    * *Sintaxis: numpy.eye(N, M=None, k=0, dtype=float, order=’C’)*

  * **identity():** Similar a la función eye(). Tienen la misma cantidad de filas y columnas.
    * *Sintaxis: numpy.identity(n, dtype=None)*

* **¿Qué tipos de datos pueden utilizarse? ¿En qué se diferencian? ¿Cuál es el tipo que se toma por defecto?¿Es siempre el mismo?**
  * El tipo de dato por defecto es float.

* **¿Qué funciones se pueden utilizar para generar arreglos con números aleatorios?**

  * Se puede utilizar numpy.random.rand()
  * np.random.seed() para una salida constante, es decir, se generan los mismos números aleatorios cada vez que se invoca la función.

### Creación de Vectores

In [1]:
import numpy as np

In [ ]:
x = np.array([x for x in range(5)])

x

array([0, 1, 2, 3, 4])

In [ ]:
x.shape

(5,)

In [ ]:
x.ndim

1

### Matrices

In [ ]:
np.random.seed(0)

matrix = np.array([
    [x for x in range(0,5)],[x for x in range(5,10)],[x for x in range(10,15)]
    ])

print(matrix)
print(f'Dimensión: {matrix.ndim}')
print(f'Cantidad de elementos: {matrix.size}')
print(f'Tamaño: {matrix.shape}')


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
Dimensión: 2
Cantidad de elementos: 15
Tamaño: (3, 5)


In [ ]:
print(f'Primer arreglo: {matrix[0]}')
print(f'Primer elemento del primer arreglo: {matrix[0][0]}')

Primer arreglo: [0 1 2 3 4]
Primer elemento del primer arreglo: 0


### 3D Matriz

In [ ]:
td = np.array([
    [np.arange(0,5), np.arange(5,10), np.arange(10,15)],
    [np.arange(15,20), np.arange(20,25), np.arange(25,30)],
    [np.arange(30,35), np.arange(35,40), np.arange(40,45)]
])

print(f'Tamaño: {td.shape}')
print(f'Dimensón: {td.ndim}')
print(f'Cantidad de elementos: {td.size}')
print(td)

Tamaño: (3, 3, 5)
Dimensón: 3
Cantidad de elementos: 45
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]]]


Sintaxis para slicing: **x[layer, row, col]**

In [ ]:
print(f'Primeras dos capas: \n{td[:2]}')

Primeras dos capas: 
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [ ]:
print(f'Primeras dos capas y últimas dos filas: \n{td[:2, -2:]}')

Primeras dos capas y últimas dos filas: 
[[[ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


In [ ]:
print(f'Primeras dos capas, útimas dos filas, columnas 3 y 4  \n{td[:2, -2:, 2:4]}')

Primeras dos capas, útimas dos filas, columnas 3 y 4  
[[[ 7  8]
  [12 13]]

 [[22 23]
  [27 28]]]


In [ ]:
print(f'Segunda capa, primer fila, 4to elemento: \n{td[1][0][3]}')

Segunda capa, primer fila, 4to elemento: 
18


In [ ]:
zeros = np.zeros([3,5])

zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
ones = np.ones([3,5])

ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
id = np.identity(5)

id

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Ejercicio 2 - Funciones relacionadas al tamaño de los arrays.

### Random size arrays

Sintaxis:
* random.randint(low, high=None, size=None, dtype=int)

https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

In [ ]:
np.random.rand(3,5)

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ],
       [0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152],
       [0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606]])

In [ ]:
np.random.randint(0, 100,size=(3,5))

array([[20, 80, 69, 79, 47],
       [64, 82, 99, 88, 49],
       [29, 19, 19, 14, 39]])

## Ejercicio 3 - funciones de agregación

### Practique funciones de agregación (sum, min, max, etc.) sobre vectores, matrices y tensores. Enumere y pruebe todas las funciones que encuentre.


In [ ]:
print(f'Suma capa 1: {td[0:1].sum()}')
print(f'Sum capa 1 fila 1: {td[:1, 0].sum()}')


Suma capa 1: 105
Sum capa 1 fila 1: 10


In [ ]:
print(f'Valor mínimo: {td.min()}')
print(f'Valor máximo: {td.max()}')

Valor mínimo: 0
Valor máximo: 44


In [ ]:
td2 = td*2

print(f'Nueva matriz con los elemn de matriz 1 multiplicados por 2: \n{td2}')

Nueva matriz con los elemn de matriz 1 multiplicados por 2: 
[[[ 0  2  4  6  8]
  [10 12 14 16 18]
  [20 22 24 26 28]]

 [[30 32 34 36 38]
  [40 42 44 46 48]
  [50 52 54 56 58]]

 [[60 62 64 66 68]
  [70 72 74 76 78]
  [80 82 84 86 88]]]


In [ ]:
print(f'Media: {np.mean(td)}')
print(f'Mediana: {np.median(td)}')
print(f'Desviación estándar: {np.std(td)}')
print(f'Varianza: {np.var(td)}')

Media: 22.0
Mediana: 22.0
Desviación estándar: 12.987173159185437
Varianza: 168.66666666666666


Índices max, min

¿Estas funciones se aplican a todos los datos del array o pueden realizarse sobre dimensiones particulares? Ejemplifique.

## Ejercicio 4 - funciones para manipular elementos de arreglos

(append, insert, delete,
etc.) y arreglos entre sí (vstack, hstack, contacenate, etc.)

https://numpy.org/doc/stable/reference/routines.array-manipulation.html

In [2]:
a1 = np.arange(0,10)
a2 = np.arange(10,20)

print(f'{a1}, \n{a2}')

[0 1 2 3 4 5 6 7 8 9], 
[10 11 12 13 14 15 16 17 18 19]


In [6]:
print(f'A1: {a1.ndim}, A2: {a2.ndim}')

A1: 1, A2: 1


In [ ]:
a3 = np.append(a1,a2)

a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

**About concanetate: **

 In NumPy, axes are numbered starting from 0. So, a 1-dimensional array only has axis 0. Trying to access axis 1 is invalid, hence the error.

In [8]:
a4 = np.concatenate((a1,a2), axis= 0)

a4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
a6 = np.array([np.arange(0,5), np.arange(5,10)])
a7 = np.array([np.arange(10,15), np.arange(15,20)])

print(f'a6: \n{a6}, \na7: \n{a7}')

a6: 
[[0 1 2 3 4]
 [5 6 7 8 9]], 
a7: 
[[10 11 12 13 14]
 [15 16 17 18 19]]


In [16]:
ap = np.append(a6,a7)

ap

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [18]:
print(f'a8 shape: {ap.shape}, ndim: {ap.ndim}')

a8 shape: (20,), ndim: 1


In [13]:
a8 = np.concatenate((a6,a7), axis=1)

a8

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [14]:
a9 = np.concatenate((a6,a7), axis=0)

a9

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [15]:
print(f'a8 shape: {a8.shape}, ndim: {a8.ndim}')
print(f'a9 shape: {a9.shape}, ndim: {a9.ndim}')

a8 shape: (2, 10), ndim: 2
a9 shape: (4, 5), ndim: 2


In [ ]:
vertical = np.vstack((a1,a2))

vertical

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [19]:
v2= np.vstack((a6,a7))

v2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
vertical.shape

(2, 10)

In [ ]:
horizontal = np.hstack((a1,a2))

horizontal.shape

(20,)

In [20]:
h2 = np.hstack((a6,a7))

h2

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [22]:
v3 = np.delete(v2, 1, axis= 0)

v3

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [23]:
v4 = np.delete(v2, 1, axis=1)

v4

array([[ 0,  2,  3,  4],
       [ 5,  7,  8,  9],
       [10, 12, 13, 14],
       [15, 17, 18, 19]])

## Ejercicio 5 - mecanismo versátil para hacer o referenciar una sección

# Pandas

pd.DataFrame(columns = ['c1', 'c2',...'cn'])

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame({
    'Nombre': ['Juan','María','Pedro', 'José'],
    'Edad': [20,26,18,22],
    'Pais': ['Argentina','Perú','Brasil', 'Chile']
})

In [ ]:
df

Nombre  Edad       Pais
0   Juan    20  Argentina
1  María    26       Perú
2  Pedro    18     Brasil
3   José    22      Chile

Realice las siguientes operaciones:
* Imprimir los nombres de las columnas.
* Agregar a la tabla a Pablo que tiene 30 años y es originario de Colombia. Agregarlo de 2 formas diferentes.
* Eliminar de la tabla al Pedro repetido.
* Modificar los atributos de países que dicen “Peru” (sin acento) y reemplazarlos por “Perú” (con acento).

In [ ]:
df.columns

Index(['Nombre', 'Edad', 'Pais'], dtype='object')

In [ ]:
import collections

Persona = collections.namedtuple('Persona', ['Nombre', 'Edad','Pais'])

d = Persona('Pablo', 30, 'Colombia')

nuevo = d._asdict()


In [ ]:
nuevo

{'Nombre': 'Pablo', 'Edad': 30, 'Pais': 'Colombia'}

In [ ]:
df = df._append(nuevo, ignore_index=True)

df

Nombre  Edad       Pais
0   Juan    20  Argentina
1  María    26       Perú
2  Pedro    18     Brasil
3   José    22      Chile
4  Pablo    30   Colombia
5   otro    30   Colombia
6  Pablo    30   Colombia

In [ ]:
df = df.drop_duplicates()

df

Nombre  Edad       Pais
0   Juan    20  Argentina
1  María    26       Perú
2  Pedro    18     Brasil
3   José    22      Chile
4  Pablo    30   Colombia
5   otro    30   Colombia

In [ ]:
# Modificar los atributos de países que dicen “Peru” (sin acento) y reemplazarlos por “Perú” (con acento)

coinciden = df.Pais == 'Perú'

coinciden

0    False
1     True
2    False
3    False
Name: Pais, dtype: bool

In [ ]:
df.loc[coinciden, 'Pais'] = 'Peru'

df

Nombre  Edad       Pais
0   Juan    20  Argentina
1  María    26       Peru
2  Pedro    18     Brasil
3   José    22      Chile